### ISSUE TITLE
if a string blockNumber "arbitrary" is passed to "eth_call" it can be that simply no results are returned. `results: undefined`. It should throw

### ISSUE THREAD

**Issue by TimDaub** [neume-network/extraction-worker#17]
- e.g. in soundxyz-metadata, when passing the blocknumber as a string number "1234", `results: undefined`: https://github.com/neume-network/strategies/blob/0bcb320bbf85c1bbf3f864fdc01f69ec34a2c416/src/strategies/soundxyz-metadata/extractor.mjs#L77
- Instead of being `undefined`, it should throw by defining `error`
- This problem doesn't occur when a hex string is passed: https://github.com/neume-network/strategies/blob/0bcb320bbf85c1bbf3f864fdc01f69ec34a2c416/src/strategies/zora-call-tokenuri/extractor.mjs#L76

**Comment by Mawittt** [comment]
hello there TimDaub I could help if I got you clearly.
so you just want the "makeRequest" function to throw an error when it receives a string as the blockNumber argument instead of an integer?

**Comment by Mawittt** [comment]
sincerely Tim I find it difficult to understand your problem here,

**Comment by il3ven** [comment]
Here is what I have understood from Tim's response. Maybe it will help @Mawittt. @TimDaub correct me if I am wrong.

We need to add a condition like below in [`extraction-worker/src/api.mjs`](https://github.com/neume-network/extraction-worker/blob/f549be170039f0e69046839488dd61f7cff0e243/src/api.mjs#L71).

```diff
if (type === "json-rpc") {
  const { method, params, options } = message;
  log(`Calling JSON-RPC endpoint with method: ${method}`);
  let results;

  try {
    results = await translate(options, method, params);
+   if (results.result === undefined) throw new Error("No result returned");
  } catch (error) {
    return cb({ ...message, error: error.toString() });
  }

  return cb(null, { ...message, results });
} else if (type === "https") {
```

The `translate` function calls [eth-fun ](https://github.com/rugpullindex/eth-fun/) which in turn calls an Ethereum RPC node. The response returned by eth-fun can be `{"jsonrpc":"2.0","id":1,"result": undefined}`. In this case extraction-worker should return a message with an error field. This can be done by simply throwing an error as above.

**Comment by il3ven** [comment]
I also think the premise of this issue is incorrect. None of the cases mentioned above return `results: undefined`.

```js
const data = encodeCallSignature(
  "tokenToEdition(uint256)",
  ["uint256"],
  ['10']
);
const to = '0x01ab7d30525e4f3010af27a003180463a6c811a6';
const res = await call(options, null, to, data, 'arbitrary');
// Error is thrown: RPCError: invalid argument 1: hex string without 0x prefix Code: -32602
```

```js
const data = encodeCallSignature(
  "tokenToEdition(uint256)",
  ["uint256"],
  ['10']
);
const to = '0x01ab7d30525e4f3010af27a003180463a6c811a6';
const res = await call(options, null, to, data, '0x1234');
// res = { jsonrpc: "2.0", id: 1, result: "0x"}
```

We can still add a check for `results: undefined`. Even though the above two scenarios don't return undefined there can be other scenarios.

**Comment by TimDaub** [comment]
> * e.g. in soundxyz-metadata, when passing the blocknumber as a string number "1234", `results: undefined`:

The original description is correct as this call returns "undefined" in eth-fun when adding block tag number "1234". But it was wrong to open this issue at neume-network/extraction-worker. Or let's say unclear description: I'm now closing it and reopening over at eth-fun.

Here's the eth-fun branch that shows the error: https://github.com/rugpullindex/eth-fun/pull/36
