### ISSUE TITLE
panic returns context free error in false message object

### ISSUE THREAD

**Issue by TimDaub** [neume-network/extraction-worker#34]
https://github.com/neume-network/extraction-worker/blob/bad307c0e63e2f48d875734620a092d62f76bedb/src/worker.mjs#L13

```
{
  error: 'Error: Request to url "https://xkcd.com/2642/info.0.json" with method "GET" and body "undefined" unsuccessful with status: 404 and answer: "<html>\r\n' +
    '<head><title>404 Not Found</title></head>\r\n' +
    '<body bgcolor="white">\r\n' +
    '<center><h1>404 Not Found</h1></center>\r\n' +
    '<hr><center>nginx</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n' +
    '"'
}
```

in strategies/lifecycle, we can't route this back to the respective strategy.

**Comment by il3ven** [comment]
Currently we aren't routing error messages back to strategy. Do we plan to do this in the future?

**Comment by TimDaub** [comment]
yeah I think we wanna do it, e.g. inthe get-xkcd example we want to react to a 404 Not Found error to understand when the extraction is done
