### ISSUE TITLE
`workerData.endpoints` should use neume-network/schema

### ISSUE THREAD

**Issue by TimDaub** [neume-network/extraction-worker#39]
- @neume-network/schema@0.3.1 adds a schema for config. @il3ven could it be used to validate the endpoints property from workerData? https://github.com/neume-network/schema/blob/main/changelog.md#031

**Comment by il3ven** [comment]
I am validating workerData.endpoints in neume-network/core. See https://github.com/neume-network/core/blob/11/config/src/boot.mjs#L23.

**Comment by TimDaub** [comment]
mhh interesting. I still think, given that extraction-worker has it's own API via the npm package that we should validate in there too. I see the problem of unnecessary redundancy. But IMO that's a problem of our npm package architecture. Not sure what to do about it...

**Comment by il3ven** [comment]
> given that extraction-worker has it's own API via the npm package that we should validate in there too

It makes sense. We can remove the validation from core and keep it in extraction-worker. Currently, the extraction-worker isn't getting the complete config object. It receives `config.endpoints`. We will have to pass the whole config object. We can also update the config schema to include `workerData.queue.options`.
