### ISSUE TITLE
Implement content negotiation using `Accept` and `Content-Type` header for worker

### ISSUE THREAD

**Issue by TimDaub** [neume-network/extraction-worker#51]
- See comment in PR https://github.com/neume-network/extraction-worker/pull/50#discussion_r983163568_
- We should consider implementing proper content negotiation using HTTP for e.g. application/json: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

**Comment by il3ven** [comment]
Closing this since we have decided to follow the approach in #53 i.e. try to parse JSON irrespective of the content type and only fallback to text if we fail to parse.
