### ISSUE TITLE
Implement Arweave support

### ISSUE THREAD

**Issue by TimDaub** [neume-network/extraction-worker#52]
- sound-protocol now uses Arweave to permanently store their tokenURI metadata, a real tokenURI their contracts return looks like this `ar://zUTuV0VL7w1z5cuGkBs2b-O3DRY2O2qA_ifSQqjLnzA/1`
- Similar to how we allow `ipfs://`, we should now also allow `ar://` and download the JSON content and return it to users

## What's currently still unclear

- I've looked for ways on how to download the arweave ID using an HTTPS gateway similar to how we deal with IPFS CIDs for now, but I've not managed to find an equivalent
- I've looked at the hardware requirements of running an arweave node and they seem to require lots of diskspace: https://arweaveteam.github.io/gateway/#/README?id=suggested-hardware
- I'm not aware of any cloud providers for arweave similar to infura, so the question is: before implementing this, will we need to provision arweave infrastructure first?

maybe this is helpful too: https://github.com/bitruss/awesome-arweave#services-%EF%B8%8F

**Comment by Kunkka0822** [comment]
@TimDaub  I have one question for you. I think we can download the JSON content from Arweave using http gateway similar to IPFS.
https://arweave.net/zUTuV0VL7w1z5cuGkBs2b-O3DRY2O2qA_ifSQqjLnzA/1
Is there any problem when extract data in this way?

**Comment by TimDaub** [comment]
great! I was looking into gateways but didn't find a way to locate them online. Thanks for posting this example link: Then yes, we can integrate Arweave similarly as IPFS

- add an Arweave message to /schema
- Add business logic to /extraction-worker that downloads JSON content

**Comment by Kunkka0822** [comment]
I will work on this issue

**Comment by TimDaub** [comment]
#55 has a solution
