### ISSUE TITLE
extraction worker still uses message-schema, but it has been deprecated

### ISSUE THREAD

**Issue by TimDaub** [neume-network/extraction-worker#56]
- https://github.com/neume-network/message-schema message schema has been deprecated
- but extraction worker is still using it: https://github.com/neume-network/extraction-worker/blob/880616d89cc9aa78a430466d08603c071d341bdb/package.json#L62
- also schema@0.5.0 is rather outdated and instead, the latest version should be used: https://github.com/neume-network/schema/blob/86bfe646f68a748cb51922f669956d0323a107a5/changelog.md#071

**Comment by il3ven** [comment]
Sorry for not clear commit messages. This issue has been solved in https://github.com/neume-network/extraction-worker/commit/57f641eff621e5fbe22f76c6ac52bd0cae82a38a which is now part of main.

**Comment by TimDaub** [comment]
awesome
