### ISSUE TITLE
allow extraction-worker to be used without worker_thread

### ISSUE THREAD

**Issue by il3ven** [neume-network/extraction-worker#60]
If we want other people to use extraction-worker then it makes sense to allow extraction-worker to be used without `worker_thread`. This will enable wider adoption as everyone's codebase isn't event based. The user should be able to simply call extraction-worker with a message and `await` on the result.

#### Promise based extraction worker:
```js
import { ExtractionWorker } from 'extraction-worker'

const worker = new ExtractionWorker({
  queue: {
    options: {
      concurrent: 1,
    },
  }
});

const res = await worker({
  options: {
    url: "https://httpbin.org/base64/SFRUUEJJTiBpcyBhd2Vzb21l",
    method: "GET",
  },
  version: "0.0.1",
  type: "https",
  commissioner: "index",
  results: null,
  error: null,
});
```

All the other functionality will remain the same. We will just export a new function. This will require some refactoring and I am willing to do it. I am also willing to then update the documentation for this and the existing features. What do you think @TimDaub? Worth picking?

**Comment by TimDaub** [comment]
I think doing this is a waste of time.

**Comment by TimDaub** [comment]
The functionality that you're proposing should be included in extraction-worker but it must not replace the existing functionality. We are intentionally biased towards events and worker threads and this won't change in the future.

**Comment by il3ven** [comment]
Yes, I'm only asking to add additional functionality.

```js
import { run } from 'extraction-worker'

if(isMainThread) {
  new Worker(...)
} else {
  run()
}
```

This will work as usual.
